remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
title: goodtimes | laser crew
description: Interactive showlaser technology: lasershows, laser art, laser games, laser control software
url: https://www.goodtimes.technology
