remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
title: goodtimes | laser crew
description: "open source showlaser software"
url: "https://www.goodtimes.technology"
logo: "assets/images/logo_goodtimes_smile.png"
defaults:
  - scope:
      path: ""
    values:
      custom_css: "assets/css/custom.css"
